const data = {
  english: {
    login: 'Login',
    myAccount: 'My Account',
    currentLanguage: 'English',
    search: 'Search for products',
    btnAll: 'All',
    addBtn: 'Add to cart',
    yourCart: 'Your Cart',
    cartItem: 'Item',
    cartUnitPrice: 'Unit price',
    cartUnit: 'Unit',
    subtotal: 'Subtotal:',
    cancel: 'Cancel',
    checkout: 'Checkout',
    buttonAdded: 'Added to cart',
    loginTitle: 'Login',
    loginInputUser: 'User Name',
    loginInputPass: 'Password',
    loginForgotPass: 'Forgot password?',
    loginSubmit: 'Submit',
    loginSignupText: 'Don`t have an account?',
    loginSignupLink: 'Signup',
    signupTitle: 'Signup',
    signupInputUser: 'User Name',
    signupInputEmail: 'Email',
    signupInputPass: 'Password',
    signupInput2Pass: 'Password Check',
    signupSubmit: 'Submit',
    signupLoginText: 'Already have an account?',
    signupLoginLink: 'Login',
    myAccountTitle: 'My Account',
    myAccountEmail: 'Change E-mail',
    myAccountEmailChange: 'Email',
    myAccountEmailConfirm: 'Confirm',
    myAccountPass: 'Change Password',
    myAccountPassChange: 'Password',
    myAccountPass2Change: 'Password Check',
    myAccountPassConfirm: 'Confirm',
    myAccountLogout: 'Log Out',
    loginError: 'Login or email are incorrect!',
    userBlank: 'Username cannot be blank',
    userMore: 'Username must have 6 characters or more',
    emailBlank: 'Email cannot be blank',
    emailValid: 'Email is not valid',
    passBlank: 'Password cannot be blank',
    passMore: 'Password must have one numeric, and min 8 characters',
    pass2Blank: 'Password check cannot be blank',
    passMatch: 'Passwords does not match',
    emailChanged: 'Email was changed',
    passChanged: 'Password was changed'
  },
  polish: {
    login: 'Zaloguj Się',
    myAccount: 'Moje Konto',
    currentLanguage: 'Polski',
    search: 'Czego szukasz',
    btnAll: 'Wszystko',
    addBtn: 'Dodaj do koszyka',
    yourCart: 'Twój koszyk',
    cartItem: 'Przedmiot',
    cartUnitPrice: 'Cena za sztukę',
    cartUnit: 'Ilość',
    subtotal: 'Wartość:',
    cancel: 'Anuluj',
    checkout: 'Zatwierdź',
    buttonAdded: 'Dodano do koszyka',
    loginTitle: 'Zaloguj Się',
    loginInputUser: 'Nazwa użytkownika',
    loginInputPass: 'Hasło',
    loginForgotPass: 'Zapomniałeś hasła?',
    loginSubmit: 'Zatwierdź',
    loginSignupText: 'Nie masz konta?',
    loginSignupLink: 'Zarejestruj się',
    signupTitle: 'Zarejestruj się',
    signupInputUser: 'Nazwa użytkownika',
    signupInputEmail: 'Email',
    signupInputPass: 'Hasło',
    signupInput2Pass: 'Sprawdzenie hasła',
    signupSubmit: 'Zatwierdź',
    signupLoginText: 'Posiadasz już konto?',
    signupLoginLink: 'Zaloguj się',
    myAccountTitle: 'Moje konto',
    myAccountEmail: 'Zmiana Email',
    myAccountEmailChange: 'Email',
    myAccountEmailConfirm: 'Potwierdź',
    myAccountPass: 'Zmiana hasła',
    myAccountPassChange: 'Hasło',
    myAccountPass2Change: 'Sprawdzenie hasła',
    myAccountPassConfirm: 'Zatwierdź',
    myAccountLogout: 'Wyloguj się',
    loginError: 'Nazwa użytkownika lub email nie są poprawne!',
    userBlank: ' Nazwa użytnownika nie może być pusta',
    userMore: 'Nazwa użytkownika musi zawierać minimum 8 znaków',
    emailBlank: 'Email nie może być pusty',
    emailValid: 'Email nie jest prawidłowy',
    passBlank: 'Hasło nie może być puste',
    passMore: 'Hasło musi zawierać jedną cyfre oraz minimum 8 znaków',
    pass2Blank: 'Sprawdzenie hasła nie może być puste',
    passMatch: 'Hasła nie pasują',
    emailChanged: 'Email został zmieniony',
    passChanged: 'Hasło zostało zmienione'
  }
};

export { data };
